apiVersion: apphosting.googleapis.com/v1alpha
kind: App
metadata:
  name: cooltiger-backend
spec:
  run:
    container:
      image: gcr.io/cloudrun/hello
      build:
        dockerfile: backend/Dockerfile
