// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq8xbJD1PCJ7BEqvMoJZDD8HfB4-0ykjk',
    appId: '1:304653364245:web:8eb76de748833c4e97721c',
    messagingSenderId: '304653364245',
    projectId: 'cooltiger',
    authDomain: 'cooltiger.firebaseapp.com',
    storageBucket: 'cooltiger.firebasestorage.app',
    measurementId: 'G-LN6SDH1J6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSm2DTyPlcT5TqdJpttMrdhFzc3zm1474',
    appId: '1:304653364245:android:6ac0030bf30e27cd97721c',
    messagingSenderId: '304653364245',
    projectId: 'cooltiger',
    storageBucket: 'cooltiger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZHG88x4c5ibbi9lhKltbp0v05sBaMZd4',
    appId: '1:304653364245:ios:d107d4275a6854d597721c',
    messagingSenderId: '304653364245',
    projectId: 'cooltiger',
    storageBucket: 'cooltiger.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZHG88x4c5ibbi9lhKltbp0v05sBaMZd4',
    appId: '1:304653364245:ios:d107d4275a6854d597721c',
    messagingSenderId: '304653364245',
    projectId: 'cooltiger',
    storageBucket: 'cooltiger.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq8xbJD1PCJ7BEqvMoJZDD8HfB4-0ykjk',
    appId: '1:304653364245:web:b0b1d139dd6b6a0f97721c',
    messagingSenderId: '304653364245',
    projectId: 'cooltiger',
    authDomain: 'cooltiger.firebaseapp.com',
    storageBucket: 'cooltiger.firebasestorage.app',
    measurementId: 'G-CVTYFFZX5V',
  );

}